# This file describes an application. You can have multiple applications
# in the same project.
#
# See https://docs.platform.sh/user_guide/reference/platform-app-yaml.html

# The name of this app. Must be unique within a project.
name: 'app'

# The runtime the application uses.
type: 'python:3.7'

# The build-time dependencies of the app.
dependencies:
    python3:
       pip: '20.1'
       supervisor: '*'
       #pipenv: '2018.10.13'

runtime:
    extensions:
        - blackfire

relationships:
    database: "db:postgresql"

# The configuration of app when it is exposed to the web.
web:
    # Whether your app should speak to the webserver via TCP or Unix socket
    # https://docs.platform.sh/configuration/app-containers.html#upstream
    upstream:
        socket_family: unix
    # Commands are run once after deployment to start the application process.
    commands:
        start: "supervisord -n -c supervisord.conf"
        #start: "gunicorn -w 4 -b unix:$SOCKET bfdemo.wsgi:application"
    locations:
        "/":
            passthru: true
        "/static":
            root: "static"
            expires: 1h
            allow: true

# The size of the persistent disk of the application (in MB).
disk: 512

# Set a local R/W mount for logs
mounts:
    'logs':
        source: local
        source_path: logs
    'data':
        source: local
        source_path: data
    

# The hooks executed at various points in the lifecycle of the application.
hooks:
  # The build hook runs before the application is deployed, and is useful for
  # assembling the codebase.
  # pipenv install --system --ignore-pipfile
  # pip install blackfire==1.4.1-internal.35 --extra-index-url=https://packagecloud.io/blackfire-io/testing/pypi/simple -v --no-deps

  build: |
    pip install django==3.0.6
    pip install gunicorn==20.0.4
    pip install jinja2==2.11.2
    pip install requests==2.23.0
    pip install blackfire
  deploy: |
    python manage.py migrate
